version: "3.9"

networks:
  go_api_network:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - go_api_network
  go-api:
    build: .
    restart: always
    container_name: go-api
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    links:
      - redis
    depends_on:
      - redis
    networks:
      - go_api_network
  